### PR TITLE
Make server URL and secret configurable through env vars

### PR DESCRIPTION
**Pull request by mpdude**
This allows to configure the server URL and secret settings through two environment variables, `THUMBOR_URL` and `THUMBOR_SECURITY_KEY`, respectively. Their settings can even be changed at runtime, thanks to the environment variable processors (a feature added in Symfony 3.4, IIRC).

The default values used previously will still be used as fallbacks if these env vars are not set, and of course, the setting can still be overwritten in your `config.yml` as it was the case before.

### CODE REVIEW

**Review by jbouzekri — CHANGES_REQUESTED** [review]
Can you add a small mention in the README that these 2 settings can now be configured by the 2 env vars ?

**Comment by jbouzekri** [comment]
And I see that the build fails after restarting it with the XDEBUG MODE coverage env var.

**Comment by mpdude** [comment]
Updated the README and tests now work locally; Travis build pipeline is currently clogged.

**Review by jbouzekri — APPROVED** [review]
:+1:

**Comment by jbouzekri** [comment]
@mpdude : new release https://github.com/jbouzekri/PhumborBundle/releases/tag/2.2.0

**Comment by mpdude** [comment]
Thank you for your fast responses!

**Pull request merged**
