### PR TITLE
Updates, deprecation fixes and GitHub Actions CI setup

### PR DESCRIPTION
**Pull request by mpdude**
Hi there 👋🏻 ,

this PR provides the results of mpdude/phumborbundle#1, mpdude/phumborbundle#2 and mpdude/phumborbundle#3.

It
* sets up GitHub Actions to run CI tests on various current Symfony versions, 
* updates PHPUnit, 
* adds missing dependency declarations
* adds return type hints to address Symfony deprecation notices in current versions.

### CODE REVIEW

**Comment by jbouzekri** [comment]
@mpdude : thank you very much for your work. Give me a few day to review it. I should be able to do it by monday.

**Comment by mpdude** [comment]
Awesome!

I can't really help with Travis CI, but GitHub actions should run PHPUnit already. Maybe it needs a first time approval by you so that my PRs may trigger runs in your Repo?

**Comment by jbouzekri** [comment]
Done. Merged. You were right. It was because github action did not peak up the workflow from the PR to initialize itself.

I am going to tag a new major release. Thank you very much

**Comment by mpdude** [comment]
Travis failed in this PR, and I don't know about the results from Scrutinizer.

Do you still see value in using these two?

**Comment by jbouzekri** [comment]
You are right we can remove Scrutinizer.

For Travis, it succeeded https://app.travis-ci.com/github/jbouzekri/PhumborBundle when I merged your PR.

**Comment by mpdude** [comment]
Yes, but does it add value over running PHPUnit tests in GitHub Actions?

**Comment by mpdude** [comment]
We can discuss this in #22 .

**Pull request merged**
